spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: main_service_route
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/**