spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main_service
          uri: lb://main-service
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
server:
  port: 8080
  logging:
    level:
      root: DEBUG