spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://event-and-additional-db:5432/ewm-event-and-additional
    username: root
    password: root
  sql:
    init:
      mode: always
stat-server:
  uri: http://stats-server:9090
grpc:
  client:
    collector:
      discovery:
        enabled: true
      serviceId: collector
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      discovery:
        enabled: true
      serviceId: analyzer
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext